FROM node:22-alpine AS build
WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml ./

RUN pnpm i

COPY . ./

FROM node:22-alpine
WORKDIR /app

COPY --from=build /app/ ./

ENV PORT=80
ENV HOST=0.0.0.0

EXPOSE 80

RUN corepack enable

CMD ["pnpm", "run", "dev"]